version: "3.9"

services:
  backend:
    build: ./backend
    container_name: pokemon_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app          # code Python pour dev
      - ./backend/data:/app/data       # données persistantes (SQLite, images)